### 1. I sing in with login/password
POST http://localhost:3000/login
Content-Type: application/json

{
    "login": "admin",
    "password": "123"
}

# as result I will return token:
#  {"token": "123"}
#
# for all next request you should put this token to cookie set.

### 2. I create a new training
POST http://localhost:3000/trainings
Content-Type: application/json
Cookie: token=123

{
    "name": "thuersday"
}

# as result get training_id:
# {
#    id: 1,
#    name: "thuersday",
#    date: "19.02.2024",
#    created_at: "19.02.2024 10:00"
# }
#

### 3. I chose exercise (with id 5) and add it to training
POST http://localhost:3000/trainings/2/exercises/3
Content-Type: application/json
Cookie: token=123
# 
# as result get response 201 with empty response

### 4. Get training 
GET http://localhost:3000/trainings/2
Content-Type: application/json
Cookie: token=123
#

### 4. I add a new repeats on frontend until end of current exercise
POST http://localhost:3000/trainings/2/exercises/3/sets
Content-Type: application/json
Cookie: token=123

[
    {
        "weight": 30,
        "repeats": 12
    },
    {
        "weight": 45,
        "repeats": 12
    }
]
### as result you will get response 201 with empty response


## 5. I after save the windows with exercise closed 
## and again we move to page where we can chose next exercise or complete training
## to finish training I will send
POST http://localhost:3000/trainings/1/complete
Content-Type: application/json
Cookie: token=123


#as result you will get 201 with empty response


### 6. Get full information about current training
GET http://localhost:3000/trainings/2
Cookie: token=123

###The result will be contain all exercises:
```
{
    id: 1,
    name: "thuersday",
    date: "19.02.2024",
    created_at: "19.02.2024 10:01",
    finished_at: "19.02.2024 11:01",
    exercises: [
        {
            exercise: 1,
            sets: [
                {
                   weight: 30,
                    repeats: 12
                },
                {
                    weight: 40,
                    repeats: 12
                }
            ]
        },
        {
            exercise: 24,
            sets: [
                {
                   weight: 35,
                    repeats: 12
                },
                {
                    weight: 45,
                    repeats: 10
                }
            ]
        },
    }]
}
```

### 8. Get all exercises:
GET http://localhost:3000/exercises
Content-Type: application/json
Cookie: token=123

#### 9. Add new exercise
POST http://localhost:3000/exercises
Content-Type: application/json
Cookie: token=123

{
   "name": "exercise name"
}

